---
box: ubuntu/trusty64
networking:
  bridge: en0
  netmask: 255.255.255.0
  address: 192.168.10.10
resources:
  memory: 4096
  vcpus: 2
  storage: 65536
devstack:
  release: master
  password: enrique
  git_base: https://github.com/openstack
  services:
    - name: rally
      active: false
    - name: tempest
      active: false
    - name: swift
      active: true
    - name: ceilometer
      active: false
    - name: ceph
      active: false
    - name: ironic
      active: false
    - name: sahara
      active: true
    - name: trove
      active: false
    - name: zaqar
      active: false
    - name: heat
      active: true
    - name: magnum
      active: true
    - name: senlin
      active: false
    - name: searchlight
      active: true
    - name: murano
      active: true
    - name: designate
      active: false
