---
box: ubuntu/trusty64
networking:
  bridge: en0
  netmask: 255.255.255.0
  address: 192.168.10.10
resources:
  memory: 4096
  vcpus: 2
  storage: 65536
devstack:
  release: master
  password: enrique
  git_base: https://github.com
  services:
    - name: keystone
      services: key
#      release: rc-1
#      repo: https://github.com/engapa/keystone
    - name: nova
      services: n-api n-cpu n-cond n-sch n-novnc n-cauth
    - name: glance
      services: g-api g-reg
    - name: cinder
      services: c-sch c-api c-vol
    - name: neutron
      services: q-svc q-dhcp q-meta q-agt q-l3
    - name: horizon
      services: horizon
    - name: thirdparties
      services: rabbit mysql dstat
#    - name: ironic
#      services: ir-api ir-cond
    - name: heat
#      services: h-eng h-api h-api-cfn h-api-cw
      plugin: true
      env:
       - IMAGE_URLS+: ",http://ftp.cica.es/fedora/linux/releases/25/CloudImages/x86_64/images/Fedora-Cloud-Base-25-1.3.x86_64.qcow2"
#    - name: swift
#      services: s-proxy s-object s-container s-account
#      env:
#       - SWIFT_HASH: "$SERVICE_PASSWORD"
#       - SWIFT_REPLICAS: 1
#       - SWIFT_STORAGE_IPS: "192.168.1.10 192.168.1.11 192.168.1.12"
#    - name: ceph
#      services: ceph
#      env:
#       - CINDER_DRIVER=ceph
#       - CINDER_ENABLED_BACKENDS=ceph
#    - name: trove
#      services: trove tr-tmgr tr-cond tr-api
#    - name: ceilometer
#      services: >
#        ceilometer-acompute ceilometer-acentral ceilometer-anotification ceilometer-collector ceilometer-api
#        ceilometer-alarm-notifier ceilometer-alarm-evaluator
#      env:
#       - CEILOMETER_BACKEND: mongodb
#       - CEILOMETER_NOTIFICATION_TOPICS: notifications,profiler
#    - name: searchlight
#      services: searchlight-api searchlight-listener
#    - name: sahara
#    - name: sahara-dashboard
#    - name: trove
#    - name: trove-dashboard
#    - name: zaqar
#    - name: magnum
#    - name: magnum-ui
#    - name: senlin
#    - name: senlin-dashboard
#    - name: murano
#    - name: designate
#    - name: aodh
#    - name: rally
#    - name: tempest