---
box: ubuntu/trusty64
networking:
  bridge: en0
  netmask: 255.255.255.0
  address: 192.168.10.10
resources:
  memory: 6096
  vcpus: 2
  storage: 65536
#provider:
#  openstack:
#    endpoint: https://indetiy.url:5000/v2
#    username: user
#    password: secret
#    tenant_name: DoO
#    server_name: devstack
#    flavor: m1.medium
#    image: ubuntu-14
#    floating_ip_pool: public
#    networks:
#     - net1
#    keypair_name: mykeypair
#    security_groups:
#     - default
devstack:
  release: master
  password: enrique
  git_base: https://github.com
  services:
    - name: keystone
#      release: rc-1
#      repo: https://github.com/engapa/keystone
    - name: nova
    - name: glance
    - name: cinder
    - name: neutron
    - name: horizon
#    - name: ironic
#    - name: heat
#    - name: swift
#    - name: trove
#    - name: ceilometer
#    - name: searchlight
#    - name: sahara
#    - name: trove
    - name: zaqar
    - name: magnum
#    - name: senlin
#    - name: murano
    - name: designate
#    - name: aodh
#    - name: rally
#    - name: tempest
    - name: thirdparties
